[root@vmi2390455 sam]# docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED        STATUS                   PORTS                                    NAMES
d8f30aa19aa0   local/sam-backend:dev              "uvicorn backend.mai…"   2 hours ago    Up 2 hours (unhealthy)   0.0.0.0:8000->8000/tcp                   compose-backend-1
ec6f68d2213f   quay.io/keycloak/keycloak:22.0.1   "/opt/keycloak/bin/k…"   2 hours ago    Up 2 hours (unhealthy)   8443/tcp, 0.0.0.0:8081->8080/tcp         keycloak
7b1d90eb0a37   local/sam-frontend:dev             "python -m http.serv…"   2 hours ago    Up 2 hours               0.0.0.0:8090->8000/tcp                   compose-frontend-1
76faa6300fe2   local/sam-client-portal:dev        "docker-entrypoint.s…"   2 hours ago    Up 2 hours               0.0.0.0:5173->3000/tcp                   compose-client-portal-1
9631688662f0   postgres:16-alpine                 "docker-entrypoint.s…"   24 hours ago   Up 24 hours (healthy)    5432/tcp                                 compose-postgres-1
b0cdfdf91899   redis:7-alpine                     "docker-entrypoint.s…"   24 hours ago   Up 24 hours (healthy)    6379/tcp                                 compose-redis-1
0c795dd2d567   prom/prometheus:v2.55.0            "/bin/prometheus --c…"   35 hours ago   Up 35 hours              0.0.0.0:9090->9090/tcp                   compose-prometheus-1
da0104c8a5cc   bitnami/zookeeper:3.9              "/opt/bitnami/script…"   35 hours ago   Up 35 hours              2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp   compose-zookeeper-1
d2a97aef8817   bitnami/kafka:3.7                  "/opt/bitnami/script…"   35 hours ago   Up 35 hours              9092/tcp                                 compose-kafka-1
2b3daff8b89c   grafana/grafana:11.1.0             "/run.sh"                35 hours ago   Up 35 hours              0.0.0.0:3001->3000/tcp                   compose-grafana-1
101308e7791c   minio/mc:latest                    "/bin/sh -c ' echo '…"   2 weeks ago    Up 2 weeks                                                        minio-client
9864a7b37372   minio/minio:latest                 "/usr/bin/docker-ent…"   2 weeks ago    Up 2 weeks (healthy)     0.0.0.0:9000-9001->9000-9001/tcp         minio-server
f219b96258b5   txe-web_app                        "docker-entrypoint.s…"   6 weeks ago    Up 6 weeks               0.0.0.0:3002->3002/tcp                   txe-web_app_1
b76b69afa727   website_app                        "docker-entrypoint.s…"   4 months ago   Up 4 months              0.0.0.0:3000->3000/tcp                   website_app_1
[root@vmi2390455 sam]# docker logs d8f30aa19aa0
INFO:     Will watch for changes in these directories: ['/app']
WARNING:  "workers" flag is ignored when reloading is enabled.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pydantic_settings/sources/base.py", line 490, in __call__
    field_value = self.prepare_field_value(field_name, field, field_value, value_is_complex)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic_settings/sources/providers/env.py", line 120, in prepare_field_value
    raise e
  File "/usr/local/lib/python3.11/site-packages/pydantic_settings/sources/providers/env.py", line 117, in prepare_field_value
    value = self.decode_complex_value(field_name, field, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic_settings/sources/base.py", line 186, in decode_complex_value
    return json.loads(value)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/backend/main.py", line 20, in <module>
    from core.config import settings
  File "/app/backend/core/config.py", line 201, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic_settings/main.py", line 189, in __init__
    **__pydantic_self__._settings_build_values(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic_settings/main.py", line 424, in _settings_build_values
    source_state = source()
                   ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic_settings/sources/base.py", line 492, in __call__
    raise SettingsError(
pydantic_settings.exceptions.SettingsError: error parsing value for field "ALLOWED_ORIGINS" from source "EnvSettingsSource"
[root@vmi2390455 sam]# docker logs ec6f68d2213f
Updating the configuration and installing your custom providers, if any. Please wait.
2025-09-05 13:53:32,014 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
2025-09-05 13:53:34,981 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2025-09-05 13:53:40,862 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2025-09-05 13:54:16,583 WARN  [org.keycloak.quarkus.runtime.KeycloakMain] (main) Running the server in development mode. DO NOT use this configuration in production.